# Automation Identity — the `claude` macOS account
#
# Creates the second local account that AI harnesses run under. The account is
# hidden from the login window, sits in `staff` (gid 20) and NOT in `admin`, so
# it holds no `(ALL) ALL` sudo grant and reads the operator's files only where
# they are group-readable. Hiding a path from it is `chmod 700 <path>` by the
# operator — nothing to declare here.
#
# ⚠️ DELETION FOOTGUN: `users.knownUsers` is the list of accounts nix-darwin
# manages. Removing this name from it does not "stop managing" the account —
# the next activation runs `sysadminctl -deleteUser`, which deletes the account
# and, with this repo's home-manager `backupCommand`, its home directory. To
# stop granting the account capabilities while keeping it, remove those grants
# and leave this module in place.
#
# There is no `users.users.<name>.extraGroups` option in nix-darwin.
# Supplementary group membership is declared as `users.groups.<g>.members`.

{ hostConfig, pkgs, ... }:

let
  userConfig = import ../../lib/user-config.nix;
  inherit (userConfig) agentUser;

  # The flake reference the grant below is pinned to. Composed from the
  # account's home, its checkout path and the host registry, so the committed
  # text carries no absolute path and no host name, and each host generates
  # the rule for itself.
  flakeRef = "${agentUser.homeDir}/${agentUser.checkout}#${hostConfig.hostName}";
in
{
  users.knownUsers = [ agentUser.name ];

  users.users.${agentUser.name} = {
    inherit (agentUser) name uid;

    # staff — the operator's primary group, and the whole of the read story.
    gid = 20;

    home = agentUser.homeDir;
    createHome = true;

    # Keep the account off the login window; sessions start with `sudo -u`.
    isHidden = true;

    description = "Automation identity";

    # programs.zsh.enable is already true (modules/darwin/common.nix).
    shell = pkgs.zsh;
  };

  # ==========================================================================
  # Passwordless sudo: converge, for the automation account only
  # ==========================================================================
  # One command, one flake reference, one host. The rule matches on the
  # invoking user, so a process running as the operator cannot use it; the
  # operator's own `darwin-rebuild` stays password-gated (see
  # modules/darwin/security.nix) and Touch ID remains the gate on `sudo -u`
  # into this account, because `timestamp_timeout=0` is set globally
  # (modules/darwin/sudo-touchid.nix) and NOPASSWD rules never consult the
  # timestamp anyway.
  #
  # The command is the `/run/current-system` symlink, never the store path
  # behind it — that path changes with every generation, so pinning it would
  # make the rule stop matching after the first converge.
  #
  # Validate the generated file before activating a change to it:
  #   darwin-rebuild build --flake .#<host>
  #   sudo visudo -cf result/etc/sudoers.d/agent-converge
  environment.etc."sudoers.d/agent-converge".text = ''
    # Generated by nix-darwin - do not edit manually
    ${agentUser.name} ALL=(ALL) NOPASSWD: /run/current-system/sw/bin/darwin-rebuild switch --flake ${flakeRef}
  '';
}
