# Cluster-Link Prep — static Thunderbolt RDMA link configuration
#
# The two-Mac clustered mode runs Apple RDMA over a direct Thunderbolt cable.
# JACCL's rendezvous parser is IPv4-only (verified 2026-07-11: every IPv6
# form, including [::1]:port, fails with "Can't parse address"), so the link
# uses role-derived synthetic IPv4 addresses. They are module-defined
# defaults on a deliberately-non-LAN /24 — not site topology; the canonical
# copy lives in nix-ai `programs.mlx.clusterMode.staticLinkIps` and these
# defaults must match it.
#
# Everything is applied ONCE at activation (root) — there is no runtime
# daemon. macOS SystemConfiguration persists the settings:
#   1. The "Thunderbolt Bridge" network service is disabled, so macOS never
#      enslaves a Thunderbolt port into bridge0 (RDMA needs exclusive L2).
#   2. Every physical Thunderbolt port's network service gets the SAME manual
#      role IPv4. Only one port is ever cabled to the peer, and inactive
#      services install no routes, so whichever port the cable lands in
#      carries the address — moving the cable needs no config change.
#
# The wired-memory ceiling flip around rank start/stop lives with the
# cluster watcher (nix-ai, user agent); sysctl needs root, so this module
# emits exact-value sudoers grants for it.

{
  lib,
  config,
  pkgs,
  ...
}:

let
  cfg = config.system.clusterLinkPrep;
  userConfig = import ../../lib/user-config.nix;
  # Day-serving wired ceiling the watcher restores at link-down: the
  # appleSiliconTunables value when that module is enabled, else 0 (= macOS
  # default ceiling).
  tunables = config.system.appleSiliconTunables;
  dayWiredLimitMb = if tunables.enable then tunables.wiredLimitMb else 0;
  prepPkg = pkgs.writeShellApplication {
    name = "cluster-link-prep";
    text = builtins.readFile ./scripts/cluster-link-prep.sh;
  };
  alfAllowPkg = pkgs.writeShellApplication {
    name = "cluster-alf-allow";
    text = builtins.readFile ./scripts/cluster-alf-allow.sh;
  };
in
{
  options.system.clusterLinkPrep = {
    enable = lib.mkEnableOption "static Thunderbolt RDMA link configuration (bridge service off, role IPv4 on every Thunderbolt port)";

    role = lib.mkOption {
      type = lib.types.enum [
        "coordinator"
        "worker"
      ];
      description = "Cluster role; selects which link address this host's Thunderbolt ports carry.";
    };

    linkIps = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      default = {
        # Synthetic point-to-point net for the Thunderbolt cable itself —
        # must match the nix-ai clusterMode.staticLinkIps defaults (canonical).
        coordinator = "192.168.208.1";
        worker = "192.168.208.2";
      };
      description = "Link addresses of the two ends of the Thunderbolt cable.";
    };

    clusterWiredLimitMb = lib.mkOption {
      type = lib.types.nullOr lib.types.int;
      default = null;
      example = 90000;
      description = ''
        iogpu.wired_limit_mb to hold while a cluster rank is serving — sized
        for this node's pipeline SHARD plus KV headroom, never the whole
        pooled model, and low enough that the GUI working set stays unwirable
        (the 2026-07-12 panic was a ~99 GB shard wiring out WindowServer).
        The cluster watcher (nix-ai) applies it before rank start and
        restores the day value (appleSiliconTunables.wiredLimitMb, else the
        macOS default) at link-down, via the exact-value sudoers grants this
        module emits. null = no grants, watcher never touches the sysctl.
        Values are UNVALIDATED until the first supervised plug session.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # Exact-value grants only: a wildcard on the value would let any user
    # process wire arbitrary amounts (and sudoers globs can span spaces,
    # opening injection of additional sysctl assignments).
    environment.etc."sudoers.d/cluster-wired-limit" = lib.mkIf (cfg.clusterWiredLimitMb != null) {
      text = ''
        # Cluster/day wired-ceiling flips for the mlx cluster watcher.
        # Generated by nix-darwin - do not edit manually
        ${userConfig.user.name} ALL=(ALL) NOPASSWD: /usr/sbin/sysctl -w iogpu.wired_limit_mb=${toString cfg.clusterWiredLimitMb}
        ${userConfig.user.name} ALL=(ALL) NOPASSWD: /usr/sbin/sysctl -w iogpu.wired_limit_mb=${toString dayWiredLimitMb}
      '';
    };

    # postActivation (root, boot + rebuild): idempotent one-shot link config;
    # never allowed to fail activation.
    system.activationScripts.postActivation.text = lib.mkAfter ''
      CLUSTER_LINK_IP=${
        lib.escapeShellArg cfg.linkIps.${cfg.role}
      } ${lib.getExe prepPkg} || echo "cluster-link-prep: non-fatal failure (see log above)"
      # The JACCL rendezvous listener needs an explicit application-firewall
      # allowance (uv CPython is ad-hoc-signed) — see scripts/cluster-alf-allow.sh.
      CLUSTER_USER_HOME="${userConfig.user.homeDir}" ${lib.getExe alfAllowPkg} || echo "cluster-alf-allow: non-fatal failure (see log above)"
    '';
  };
}
