# Window-gated darwin-rebuild.
#
# When enabled, installs darwin-rebuild-windowed (./scripts/darwin-rebuild-windowed.sh)
# and renders one sudoers NOPASSWD line for the operator user. That line runs the
# wrapper for this host only. The wrapper performs `darwin-rebuild switch` after an
# OpenBao window token and the cluster state both pass its checks.
#
# Disabled by default, in which case no grant for darwin-rebuild exists (see
# security.nix). The grant names the wrapper's exact store path and the configured
# host name, so sudo refuses any other argument list before the wrapper runs.
{
  lib,
  config,
  pkgs,
  ...
}:

let
  userConfig = import ../../lib/user-config.nix;
  cfg = config.security.darwinRebuildWindowed;

  wrapper = pkgs.writeShellApplication {
    name = "darwin-rebuild-windowed";
    runtimeInputs = [ pkgs.jq ];
    # writeShellApplication exports these unconditionally, so they override any
    # value the caller's environment carries.
    runtimeEnv = {
      DARWIN_REBUILD_WINDOWED_BAO_ADDR_FILE = cfg.baoAddrFile;
      DARWIN_REBUILD_WINDOWED_CLUSTER_STATE_DIR = cfg.clusterStateDir;
      DARWIN_REBUILD_WINDOWED_DARWIN_REBUILD_BIN = "/run/current-system/sw/bin/darwin-rebuild";
      DARWIN_REBUILD_WINDOWED_CURL_BIN = "/usr/bin/curl";
      DARWIN_REBUILD_WINDOWED_LOGGER_BIN = "/usr/bin/logger";
      DARWIN_REBUILD_WINDOWED_TRUSTED_UID = "0";
      DARWIN_REBUILD_WINDOWED_FLAKE_REF = cfg.flakeRef;
    };
    text = builtins.readFile ./scripts/darwin-rebuild-windowed.sh;
  };
in
{
  options.security.darwinRebuildWindowed = {
    enable = lib.mkEnableOption "the window-gated darwin-rebuild wrapper and its sudoers grant";

    hostname = lib.mkOption {
      type = lib.types.strMatching "[a-z0-9-]+";
      default = config.networking.hostName;
      description = "Host name the sudoers grant accepts. Must equal this host's flake attribute name.";
    };

    flakeRef = lib.mkOption {
      type = lib.types.strMatching "github:[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+";
      description = "Flake the wrapper switches to, as github:<owner>/<repo> without an attribute; the host name is appended as #<hostname>. Set by the host configuration.";
    };

    baoAddrFile = lib.mkOption {
      type = lib.types.strMatching "/.+";
      default = "/etc/darwin-rebuild-windowed/bao-addr";
      description = "Absolute path of a file containing BAO_ADDR=https://... . The file and its directory must be owned by root and writable by no other uid.";
    };

    clusterStateDir = lib.mkOption {
      type = lib.types.strMatching "/.+";
      default = "${userConfig.user.homeDir}/Library/Application Support/mlx-cluster";
      description = "Absolute path of the directory holding link-state and peer-state.json. Missing files count as not clustered.";
    };
  };

  config = lib.mkIf cfg.enable {
    environment.systemPackages = [ wrapper ];

    environment.etc."sudoers.d/darwin-rebuild-windowed".text = ''
      # Allow ${userConfig.user.name} to run the window-gated darwin-rebuild for this host only.
      # Generated by nix-darwin - do not edit manually
      ${userConfig.user.name} ALL=(root) NOPASSWD: ${wrapper}/bin/darwin-rebuild-windowed ${cfg.hostname}
    '';
  };
}
