# Minimal pf inbound baseline on top of the application firewall.
#
# The ALF (networking.applicationFirewall) is per-application and stealth
# mode is deliberately off (hosts/common/default.nix) so LAN services keep
# answering. This adds a packet-filter anchor loaded at boot by a launchd
# daemon: default-deny inbound on the Wi-Fi/Ethernet/Thunderbolt-Bridge
# interfaces except established connections, ICMP echo, and SSH from an
# allow-listed CIDR set. Loopback and the cluster link (bridge0 + every
# enX Thunderbolt port — see cluster-link-prep.nix) are always passed so
# RDMA cluster traffic is never touched by this anchor.
{
  lib,
  config,
  pkgs,
  ...
}:

let
  cfg = config.security.pf;
  anchorPath = "/etc/pf.anchors/nix-hardening";

  anchorText = ''
    # Generated by nix-darwin (modules/darwin/pf-hardening.nix) - do not edit manually
    #
    # Cluster link (bridge0 + every Thunderbolt enX port RDMA can use) and
    # loopback are fully exempt so this anchor can never block cluster
    # traffic. Everything else default-denies inbound except established
    # state, ICMP echo, and SSH from the allow-listed CIDRs below.
    set skip on { lo0, bridge0, en0, en1, en2, en3, en4, en5, en6, en7, en8, en9 }
    block in all
    pass out all keep state
    pass in quick proto tcp to port 22 from { ${lib.concatStringsSep ", " cfg.allowedSshSources} } flags S/SA keep state (max-src-conn 10)
    pass in quick inet proto icmp icmp-type echoreq keep state
  '';

  loadAnchor = pkgs.writeShellApplication {
    name = "pf-hardening-load";
    text = ''
      /sbin/pfctl -a nix-hardening -f ${anchorPath} 2>&1
      /sbin/pfctl -e 2>&1 || true
    '';
  };
in
{
  options.security.pf.allowedSshSources = lib.mkOption {
    type = lib.types.listOf lib.types.str;
    # ponytail: single broad RFC1918 default, narrow per-fleet CIDR if a
    # tighter allow-list is ever needed.
    default = [ "10.0.0.0/8" ];
    description = "CIDRs permitted to reach TCP/22 through the pf anchor.";
  };

  config = {
    environment.etc."pf.anchors/nix-hardening".text = anchorText;

    launchd.daemons.pf-hardening = {
      serviceConfig = {
        Label = "com.nix-darwin.pf-hardening";
        ProgramArguments = [ (lib.getExe loadAnchor) ];
        RunAtLoad = true;
        StandardOutPath = "/var/log/pf-hardening.log";
        StandardErrorPath = "/var/log/pf-hardening.log";
      };
    };
  };
}
