# Minimal pf inbound baseline on top of the application firewall.
#
# The ALF (networking.applicationFirewall) is per-application and stealth
# mode is deliberately off (hosts/common/default.nix) so LAN services keep
# answering. This adds a packet-filter anchor loaded at boot by a launchd
# daemon: default-deny inbound except established connections, ICMP echo,
# SSH from an allow-listed CIDR set, and traffic on explicitly exempted
# interfaces (loopback, plus anything named in security.pf.exemptInterfaces).
#
# flake.nix's aarch64-darwin checks build environment.etc."pf.anchors/
# nix-hardening".text straight from the real host config and run
# `pfctl -n -f` (syntax-only parse) against it, so a bad anchor here fails
# `nix flake check` instead of shipping.
{
  lib,
  config,
  pkgs,
  ...
}:

let
  cfg = config.security.pf;
  anchorPath = "/etc/pf.anchors/nix-hardening";

  anchorText = ''
    # Generated by nix-darwin (modules/darwin/pf-hardening.nix) - do not edit manually
    #
    # `set skip` is NOT valid inside an anchor loaded via
    # `pfctl -a <name> -f <file>` (anchors carry filter/scrub rules only,
    # not top-level pf.conf options) — exemptions are plain `pass quick on
    # <iface>` rules instead, evaluated before the default-deny below.
    ${lib.concatMapStrings (iface: "pass quick on ${iface} all\n") cfg.exemptInterfaces}
    block in all
    pass out all keep state
    pass in quick proto tcp from { ${lib.concatStringsSep ", " cfg.allowedSshSources} } to any port 22 flags S/SA keep state (max-src-conn 10)
    pass in quick inet proto icmp icmp-type echoreq keep state
  '';

  loadAnchor = pkgs.writeShellApplication {
    name = "pf-hardening-load";
    text = ''
      # writeShellApplication already sets -euo pipefail: a failure below
      # (bad anchor syntax, pfctl missing) aborts and launchd records a
      # non-zero exit instead of silently leaving pf unloaded.
      if ! /sbin/pfctl -a nix-hardening -f ${anchorPath} 2>&1 | /usr/bin/tee >(/usr/bin/logger -t pf-hardening); then
        /usr/bin/logger -t pf-hardening "FAILED to load ${anchorPath} - pf anchor NOT active"
        exit 1
      fi
      /sbin/pfctl -e 2>&1 | /usr/bin/logger -t pf-hardening || true
      /usr/bin/logger -t pf-hardening "anchor nix-hardening loaded and pf enabled"
    '';
  };
in
{
  options.security.pf = {
    allowedSshSources = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      # ponytail: single broad RFC1918 default, narrow per-fleet CIDR if a
      # tighter allow-list is ever needed.
      default = [ "10.0.0.0/8" ];
      description = "CIDRs permitted to reach TCP/22 through the pf anchor.";
    };

    exemptInterfaces = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [
        "lo0"
        "bridge0"
      ];
      description = ''
        Interfaces fully exempt from the pf anchor's default-deny (`pass
        quick on <iface> all`, evaluated first). Loopback plus bridge0 —
        the Thunderbolt Bridge network-service device cluster-link-prep.nix
        keeps disabled/unenslaved for RDMA exclusivity, so this entry
        currently matches no live traffic, but stays declared for the
        window cluster-link-prep briefly touches bridge0 during its sweep.
        Deliberately NOT a wildcard en* glob: that would exempt the primary
        LAN NIC (en0) from the entire ruleset, defeating the default-deny.
        The actual Thunderbolt RDMA link runs on whichever physical enN port
        is cabled (varies per host, never a fixed name — see
        cluster-link-prep.nix), so it is NOT covered by this list; it rides
        the synthetic 192.168.208.0/x point-to-point net between the two
        hosts, distinct from the LAN this anchor is guarding.
      '';
    };
  };

  config = {
    environment.etc."pf.anchors/nix-hardening".text = anchorText;

    launchd.daemons.pf-hardening = {
      serviceConfig = {
        Label = "com.nix-darwin.pf-hardening";
        ProgramArguments = [ (lib.getExe loadAnchor) ];
        RunAtLoad = true;
        StandardOutPath = "/var/log/pf-hardening.log";
        StandardErrorPath = "/var/log/pf-hardening.log";
      };
    };
  };
}
