# Security Configuration
#
# CRITICAL: This file contains security-sensitive settings.
# Changes here affect system-level permissions and should be reviewed carefully.
#
# Current security policies:
# - Passwordless sudo for darwin-rebuild and system activation (enables AI assistants)
# - Passwordless sudo for Thunderbolt-RDMA / cluster troubleshooting commands
#   (enables unattended cluster bring-up recovery)

{ lib, ... }:

let
  userConfig = import ../../lib/user-config.nix;

  # ==========================================================================
  # Cluster / RDMA launchd targets
  # ==========================================================================
  # The two-Mac Thunderbolt-RDMA cluster (see night-link.nix, night-link-prep.nix)
  # is driven by launchd services under these label prefixes. `gui/501` is
  # ${userConfig.user.name}'s login-session domain (uid 501, the sole macOS
  # account on both hosts — launchd's gui/<uid> syntax needs the literal
  # numeric uid; it cannot be derived at sudoers-match time).
  clusterLaunchdTargets = [
    {
      domain = "system";
      labelGlob = "dev.night-link.*";
    }
    {
      domain = "gui/501";
      labelGlob = "dev.mlx-night.*";
    }
    {
      domain = "gui/501";
      labelGlob = "dev.vllm-mlx.*";
    }
  ];

  # One NOPASSWD line per target/verb pair. Trade-off: the `*` glob is
  # coarser than an exact label match on bootstrap/kill (sudoers has no way
  # to say "any signal" or "any plist path" more precisely than a wildcard),
  # but every rule stays scoped to the three cluster label prefixes above —
  # never a bare `launchctl` grant.
  clusterLaunchdRules = lib.concatMapStrings (t: ''
    ${userConfig.user.name} ALL=(ALL) NOPASSWD: /bin/launchctl kickstart -k ${t.domain}/${t.labelGlob}
    ${userConfig.user.name} ALL=(ALL) NOPASSWD: /bin/launchctl bootout ${t.domain}/${t.labelGlob}
    ${userConfig.user.name} ALL=(ALL) NOPASSWD: /bin/launchctl print ${t.domain}/${t.labelGlob}
    ${userConfig.user.name} ALL=(ALL) NOPASSWD: /bin/launchctl kill * ${t.domain}/${t.labelGlob}
    ${userConfig.user.name} ALL=(ALL) NOPASSWD: /bin/launchctl bootstrap ${t.domain} *${t.labelGlob}
  '') clusterLaunchdTargets;
in
{
  # ==========================================================================
  # Passwordless sudo for darwin-rebuild and system activation
  # ==========================================================================
  # Purpose: Allow AI assistants (Claude Code, etc.) to run darwin-rebuild switch
  # and system activation without prompting for password.
  #
  # Security considerations:
  # - ONLY darwin-rebuild and activation are allowed passwordless
  # - darwin-rebuild can only modify Nix-managed system configuration
  # - Activation only applies already-built Nix store paths
  # - All changes are declarative and version-controlled in this repo
  # - Rollback is always possible via darwin-rebuild --rollback
  #
  # Implementation: Creates /etc/sudoers.d/darwin-rebuild via environment.etc
  # nix-darwin doesn't have security.sudo.extraRules, so we use etc files
  #
  # To disable: comment out or remove the environment.etc block
  environment.etc."sudoers.d/darwin-rebuild".text = ''
    # Allow ${userConfig.user.name} to run darwin-rebuild and activate without password
    # Generated by nix-darwin - do not edit manually
    ${userConfig.user.name} ALL=(ALL) NOPASSWD: /run/current-system/sw/bin/darwin-rebuild
    ${userConfig.user.name} ALL=(ALL) NOPASSWD: /nix/var/nix/profiles/system/activate
  '';

  # ==========================================================================
  # Passwordless sudo: Thunderbolt-RDMA / cluster troubleshooting
  # ==========================================================================
  # Purpose: let an autonomous agent inspect and converge the night-cluster
  # Thunderbolt link and its launchd services without an interactive password
  # prompt, so unattended cluster bring-up recovery does not stall mid-run.
  #
  # Security considerations:
  # - launchctl access is scoped to the three cluster label prefixes above
  #   (system/dev.night-link.*, gui/501/dev.mlx-night.*, gui/501/dev.vllm-mlx.*)
  #   — never a blanket `launchctl` grant.
  # - ifconfig access is scoped to `en*` interfaces (the Thunderbolt-cabled
  #   port is auto-detected at runtime — see night-link.nix — so its exact
  #   index cannot be pinned in a static sudoers pattern) plus
  #   `bridge0 deletem en*` (manually detach a port from the Thunderbolt
  #   Bridge, mirroring the automatic activation-script step). Trade-off:
  #   this also covers the built-in en0/en1 ports, which sudoers cannot
  #   exclude by name alone.
  # - reboot/shutdown are deliberately NOT granted here; those stay
  #   interactive pending explicit user approval.
  #
  # To disable: comment out or remove the environment.etc block
  environment.etc."sudoers.d/cluster-ops".text = ''
    # Allow ${userConfig.user.name} to run cluster/RDMA troubleshooting commands
    # without password. Generated by nix-darwin - do not edit manually
    ${clusterLaunchdRules}
    ${userConfig.user.name} ALL=(ALL) NOPASSWD: /sbin/ifconfig en*
    ${userConfig.user.name} ALL=(ALL) NOPASSWD: /sbin/ifconfig bridge0 deletem en*
  '';
}
