# Security Configuration
#
# CRITICAL: This file contains security-sensitive settings.
# Changes here affect system-level permissions and should be reviewed carefully.
#
# Current security policies:
# - Passwordless sudo for darwin-rebuild and system activation (enables AI assistants)
# - Passwordless sudo for Thunderbolt-RDMA / cluster troubleshooting commands
#   (enables unattended cluster bring-up recovery)

{ lib, ... }:

let
  userConfig = import ../../lib/user-config.nix;

  # ==========================================================================
  # Cluster / RDMA launchd targets
  # ==========================================================================
  # The two-Mac Thunderbolt-RDMA cluster (see cluster-link.nix, cluster-link-prep.nix)
  # is driven by launchd services under these label prefixes. `gui/501` is
  # ${userConfig.user.name}'s login-session domain (uid 501, the sole macOS
  # account on both hosts — launchd's gui/<uid> syntax needs the literal
  # numeric uid; it cannot be derived at sudoers-match time).
  clusterLaunchdTargets = [
    {
      domain = "system";
      labelGlob = "dev.cluster-link.*";
    }
    {
      domain = "gui/501";
      labelGlob = "dev.mlx-cluster.*";
    }
    {
      domain = "gui/501";
      labelGlob = "dev.vllm-mlx.*";
    }
  ];

  # One NOPASSWD line per target/verb pair, all scoped to the three cluster
  # label prefixes above — never a bare `launchctl` grant. The `kill`/`kickstart`
  # wildcards only widen the *signal*/flag, not the target label, so they cannot
  # reach a service outside these prefixes.
  #
  # `bootstrap` is the one verb that loads a plist FROM DISK as root, so its
  # path must never resolve to attacker-controlled content:
  #   - `system` daemons live in /Library/LaunchDaemons, which is root-owned
  #     (0755 root:wheel) — a user process cannot plant or symlink a plist
  #     there, so the anchored path glob can only match the real root daemons.
  #   - `gui/501` agents live in ~/Library/LaunchAgents, which IS user-writable
  #     (0700 ${userConfig.user.name}) — a passwordless-root bootstrap of that
  #     path would be a privesc. It is also unnecessary: those agents are
  #     RunAtLoad (home-manager bootstraps them at login) and the user can
  #     bootstrap them in their own gui/501 domain without root. So no
  #     bootstrap grant is emitted for user-agent targets.
  clusterLaunchdRules = lib.concatMapStrings (
    t:
    ''
      ${userConfig.user.name} ALL=(ALL) NOPASSWD: /bin/launchctl kickstart -k ${t.domain}/${t.labelGlob}
      ${userConfig.user.name} ALL=(ALL) NOPASSWD: /bin/launchctl bootout ${t.domain}/${t.labelGlob}
      ${userConfig.user.name} ALL=(ALL) NOPASSWD: /bin/launchctl print ${t.domain}/${t.labelGlob}
      ${userConfig.user.name} ALL=(ALL) NOPASSWD: /bin/launchctl kill * ${t.domain}/${t.labelGlob}
    ''
    + lib.optionalString (t.domain == "system") ''
      ${userConfig.user.name} ALL=(ALL) NOPASSWD: /bin/launchctl bootstrap system /Library/LaunchDaemons/${t.labelGlob}
    ''
  ) clusterLaunchdTargets;
in
{
  # ==========================================================================
  # Passwordless sudo for darwin-rebuild and system activation
  # ==========================================================================
  # Purpose: Allow AI assistants (Claude Code, etc.) to run darwin-rebuild switch
  # and system activation without prompting for password.
  #
  # Security considerations:
  # - ONLY darwin-rebuild and activation are allowed passwordless
  # - darwin-rebuild can only modify Nix-managed system configuration
  # - Activation only applies already-built Nix store paths
  # - All changes are declarative and version-controlled in this repo
  # - Rollback is always possible via darwin-rebuild --rollback
  #
  # Implementation: Creates /etc/sudoers.d/darwin-rebuild via environment.etc
  # nix-darwin doesn't have security.sudo.extraRules, so we use etc files
  #
  # To disable: comment out or remove the environment.etc block
  environment.etc."sudoers.d/darwin-rebuild".text = ''
    # Allow ${userConfig.user.name} to run darwin-rebuild and activate without password
    # Generated by nix-darwin - do not edit manually
    ${userConfig.user.name} ALL=(ALL) NOPASSWD: /run/current-system/sw/bin/darwin-rebuild
    ${userConfig.user.name} ALL=(ALL) NOPASSWD: /nix/var/nix/profiles/system/activate
  '';

  # ==========================================================================
  # Passwordless sudo: Thunderbolt-RDMA / cluster troubleshooting
  # ==========================================================================
  # Purpose: let an autonomous agent inspect and converge the cluster-mode
  # Thunderbolt link and its launchd services without an interactive password
  # prompt, so unattended cluster bring-up recovery does not stall mid-run.
  #
  # Security considerations:
  # - launchctl access is scoped to the three cluster label prefixes above
  #   (system/dev.cluster-link.*, gui/501/dev.mlx-cluster.*, gui/501/dev.vllm-mlx.*)
  #   — never a blanket `launchctl` grant. `bootstrap` (the only plist-loading
  #   verb) is granted ONLY against the root-owned /Library/LaunchDaemons path;
  #   see the clusterLaunchdRules comment on why user-agent bootstrap is dropped.
  # - ifconfig grants cover only the two operations that genuinely need root:
  #   detaching a cabled port from the Thunderbolt Bridge (`bridge0 deletem`,
  #   mirroring the activation-script step) and bouncing a Thunderbolt port
  #   up/down during link recovery. Interface *reads* need no root, so plain
  #   `ifconfig enX` inspection is intentionally NOT granted. Every grant is
  #   pinned to `en[0-9]*` with a fixed verb — no arbitrary trailing args — so
  #   it can neither reassign an address, change MTU, nor destroy an interface.
  #   Trade-off: `en[0-9]*` still covers the built-in en0/en1 ports (the cabled
  #   RDMA port is auto-detected at runtime — see cluster-link.nix — so its index
  #   cannot be pinned in a static pattern), but up/down on those is recoverable
  #   and non-destructive.
  # - reboot/shutdown are deliberately NOT granted here; those stay
  #   interactive pending explicit user approval.
  #
  # To disable: comment out or remove the environment.etc block
  environment.etc."sudoers.d/cluster-ops".text = ''
    # Allow ${userConfig.user.name} to run cluster/RDMA troubleshooting commands
    # without password. Generated by nix-darwin - do not edit manually
    ${clusterLaunchdRules}
    ${userConfig.user.name} ALL=(ALL) NOPASSWD: /sbin/ifconfig bridge0 deletem en[0-9]*
    ${userConfig.user.name} ALL=(ALL) NOPASSWD: /sbin/ifconfig en[0-9]* up
    ${userConfig.user.name} ALL=(ALL) NOPASSWD: /sbin/ifconfig en[0-9]* down
  '';
}
