# sshd hardening — declarative drop-in for macOS Remote Login.
#
# services.openssh.enable (hosts/common/default.nix) turns on launchd's
# built-in sshd with Apple's stock com.apple.ssh.sshd_config, which still
# permits password auth. This ships a drop-in under sshd_config.d/ (sshd
# reads that directory in filename order and a later file overrides an
# earlier setting for the same key — 200- sorts after Apple's own 100-
# ssh-tunnel-agent style files) so key-only auth is the enforced default
# without touching the vendor file.
{
  lib,
  config,
  ...
}:

let
  userConfig = import ../../lib/user-config.nix;
  cfg = config.security.sshCaPublicKey;
in
{
  options.security.sshCaPublicKey = lib.mkOption {
    type = lib.types.nullOr lib.types.str;
    default = null;
    description = ''
      Path to an SSH CA public key (e.g. minted by an OpenBao SSH CA) to
      trust for certificate-based login via TrustedUserCAKeys. Left null
      until a CA is actually provisioned for this fleet.
    '';
  };

  config = {
    environment.etc."ssh/sshd_config.d/200-hardening.conf".text = ''
      # Generated by nix-darwin (modules/darwin/ssh-hardening.nix) - do not edit manually
      PasswordAuthentication no
      KbdInteractiveAuthentication no
      ChallengeResponseAuthentication no
      PermitRootLogin no
      PermitEmptyPasswords no
      PubkeyAuthentication yes
      MaxAuthTries 3
      LoginGraceTime 30
      X11Forwarding no
      AllowUsers ${userConfig.user.name}
    ''
    + lib.optionalString (cfg != null) "TrustedUserCAKeys ${cfg}\n";
  };
}
