# Touch ID for sudo — biometric escalation, no stored credential
#
# WHY THIS IS NOT AN ASKPASS HELPER
#
# The obvious way to let a non-interactive process reach root is SUDO_ASKPASS
# pointed at a GUI prompt (on macOS, an `osascript display dialog`). That is
# the wrong tool here and is deliberately NOT used:
#
#   - Any process running as this user can spawn a pixel-identical dialog and
#     harvest the password. The helper teaches the human to type their admin
#     password into whatever asks, which is the phishing primitive itself.
#   - The typed password transits a shell script's argv/stdin, where it is
#     readable and loggable.
#   - It yields a REUSABLE secret. Captured once, replayable forever, off-host.
#
# pam_tid has none of those properties. The prompt is drawn by the system, not
# by a script this user can imitate; the response is a fingerprint, which
# cannot be typed, copied, exfiltrated, or replayed; and nothing is stored.
# A hostile process can *ask* for escalation and still cannot obtain it without
# a physical finger on this machine.
#
# This complements, and does not undo, the posture in security.nix: sudo for
# darwin-rebuild stays authenticated. Touch ID changes only HOW the human
# proves presence, never WHETHER they must.
#
# WHAT THIS DOES NOT PROTECT AGAINST
#
#   - Consent fatigue. The system prompt says "sudo", not which command. A
#     user who touches reflexively approves whatever asked. Biometrics prove
#     presence, never intent about a specific command.
#   - Anything already covered by a NOPASSWD rule in security.nix. Those skip
#     PAM entirely and are unaffected by this file, in either direction.
#
# The credential cache is the one replay window Touch ID would otherwise leave
# open — see the timestamp_timeout note below.

{ ... }:

{
  security.pam.services.sudo_local = {
    # /etc/pam.d/sudo already begins with `auth include sudo_local`, so
    # pam_tid gets the first attempt and pam_opendirectory (password) remains
    # the fallback when a finger is unavailable — a failed or cancelled Touch
    # ID does not lock anyone out.
    touchIdAuth = true;

    # tmux and screen re-parent themselves out of the login GUI session, and
    # pam_tid is bound to that session — without this, sudo inside a
    # long-lived tmux pane silently falls back to the password prompt, which
    # is exactly the non-interactive dead end this change exists to remove.
    reattach = true;

    # Apple Watch unlock is deliberately left off. Wrist-detect plus proximity
    # is a weaker presence proof than a fingerprint, and the threat model here
    # is a hostile process on this host, where "the human is nearby" is
    # precisely the assumption that must not be sufficient.
    watchIdAuth = false;
  };

  # One touch per escalation.
  #
  # sudo's default is to cache credentials for five minutes after a successful
  # authentication. In this threat model that cache is a five-minute window in
  # which any process running as this user gets unattended root, riding an
  # approval the human granted for something else. Setting the timeout to zero
  # closes it: every sudo re-authenticates.
  #
  # The cost here is near zero, which is why this is on. The frequent
  # automation verbs (cluster/RDMA recovery, the MLX serving ladder) are all
  # NOPASSWD in security.nix and never consult the timestamp at all. What is
  # left is rare and single-shot — a converge, mostly — so "authenticate every
  # time" costs one extra touch, not a workflow.
  environment.etc."sudoers.d/timestamp-no-cache".text = ''
    # Generated by nix-darwin - do not edit manually
    Defaults timestamp_timeout=0
  '';
}
